//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task03 {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConsoleResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsoleResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Task03.ConsoleResource", typeof(ConsoleResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Площадь прямоугольника:.
        /// </summary>
        internal static string AreaRectMessage {
            get {
                return ResourceManager.GetString("AreaRectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Центр кольца: .
        /// </summary>
        internal static string CenterRingMessage {
            get {
                return ResourceManager.GetString("CenterRingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Центр окружности: .
        /// </summary>
        internal static string CenterRoundMessage {
            get {
                return ResourceManager.GetString("CenterRoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _______________________________________________________________________________.
        /// </summary>
        internal static string DividingLine {
            get {
                return ResourceManager.GetString("DividingLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный формат ввода данных..
        /// </summary>
        internal static string ErrorInputFormat {
            get {
                return ResourceManager.GetString("ErrorInputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Координаты первой точки: .
        /// </summary>
        internal static string FirstPointMessage {
            get {
                return ResourceManager.GetString("FirstPointMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Высота прямоугольника:.
        /// </summary>
        internal static string HeightRectMessage {
            get {
                return ResourceManager.GetString("HeightRectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внутренний радиус:.
        /// </summary>
        internal static string InnerRadius {
            get {
                return ResourceManager.GetString("InnerRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите точку центра.
        /// </summary>
        internal static string InputCenterRound {
            get {
                return ResourceManager.GetString("InputCenterRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите левую нижнюю точку прямоугольника.
        /// </summary>
        internal static string InputFirstPointRect {
            get {
                return ResourceManager.GetString("InputFirstPointRect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите внутренний радиус.
        /// </summary>
        internal static string InputInnerRadius {
            get {
                return ResourceManager.GetString("InputInnerRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите названия типа фигуры из списка..
        /// </summary>
        internal static string InputMessage {
            get {
                return ResourceManager.GetString("InputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите радиус .
        /// </summary>
        internal static string InputRadius {
            get {
                return ResourceManager.GetString("InputRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите правую верхнюю точку прямоугольника.
        /// </summary>
        internal static string InputSecondPointRect {
            get {
                return ResourceManager.GetString("InputSecondPointRect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Длина описанной окружности: .
        /// </summary>
        internal static string LengthBorderMessage {
            get {
                return ResourceManager.GetString("LengthBorderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Длина внутренней границы: .
        /// </summary>
        internal static string LengthInnerBorderMessage {
            get {
                return ResourceManager.GetString("LengthInnerBorderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Длина линии: .
        /// </summary>
        internal static string LengthLineMessage {
            get {
                return ResourceManager.GetString("LengthLineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Длина внешней границы: .
        /// </summary>
        internal static string LengthOuterBorderMessage {
            get {
                return ResourceManager.GetString("LengthOuterBorderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите нужную команду:.
        /// </summary>
        internal static string MenuMessage {
            get {
                return ResourceManager.GetString("MenuMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внешний радиус:.
        /// </summary>
        internal static string OuterRadius {
            get {
                return ResourceManager.GetString("OuterRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Периметр прямоугольника:.
        /// </summary>
        internal static string PerimeterRectMessage {
            get {
                return ResourceManager.GetString("PerimeterRectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Радиус окружности: .
        /// </summary>
        internal static string RadiusRoundMessage {
            get {
                return ResourceManager.GetString("RadiusRoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Координаты второй точки:.
        /// </summary>
        internal static string SecondPointMessage {
            get {
                return ResourceManager.GetString("SecondPointMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фигура успешно создана..
        /// </summary>
        internal static string SuccessAddedMessage {
            get {
                return ResourceManager.GetString("SuccessAddedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип введенной фигуры не найден..
        /// </summary>
        internal static string TypeNotFound {
            get {
                return ResourceManager.GetString("TypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ширина прямоугольника:.
        /// </summary>
        internal static string WidthRectMessage {
            get {
                return ResourceManager.GetString("WidthRectMessage", resourceCulture);
            }
        }
    }
}
